ktor:
  application:
    modules:
      - com.soquiz.ApplicationKt.module
  deployment:
    port: 8080

jwt:
  secret: $JWT_SECRET
  issuer: "https://www.soquizz.sotopatrick.com/"
  audience: "https://www.soquizz.sotopatrick.com/"
  realm: "SoQuiz Api"

postgres:
  url: "USE_ENV_VARIABLE"
  user: "USE_ENV_VARIABLE"
  password: "USE_ENV_VARIABLE"
  driver: "org.postgresql.Driver"
