ktor:
  application:
    modules:
      - com.soquiz.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  secret: ${JWT_SECRET}
  issuer: "https://www.soquizz.sotopatrick.com/"
  audience: "https://www.soquizz.sotopatrick.com/"
  realm: "SoQuiz Api"

postgres:
  url: ${POSTGRES_URL}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  driver: "org.postgresql.Driver"
