ktor:
  application:
    modules:
      - com.soquiz.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  secret: ""
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/"
  realm: "SoQuiz Api"

postgres:
  url: ""
  user: ""
  password: ""
  driver: "org.postgresql.Driver"
