name: Deploy to App Engine

on:
  push:
    branches:
      - main  # Deploys when pushing to the main branch

jobs:
  deploy:
    name: Deploy to Google App Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build the project
        run: ./gradlew clean build shadowJar

      - name: List build artifacts
        run: ls -lh build/libs/

      - name: Log environment variables
        run: |
          echo "JWT_SECRET: $JWT_SECRET"
          echo "POSTGRES_URL: $POSTGRES_URL"
          echo "POSTGRES_USER: $POSTGRES_USER"
          echo "POSTGRES_PASSWORD: $POSTGRES_PASSWORD"


      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Verify app.yaml content
        run: cat app.yaml


      - name: Deploy to App Engine
        run: |
          gcloud app deploy app.yaml --quiet --version=1 --project=${{ secrets.GCP_PROJECT_ID }}
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
